[hawkbit] update ingress version for kubernetes >= 1.14
eclipse/packages pull request #149
Opened 2020-09-30 12:22 UTC by rpahli

update ingress version to `extensions/v1beta1` for kubernetes version >= 1.14

2020-09-30 17:34 UTC, monotek requested changes

2020-09-30 17:34 UTC, monotek commented on charts/hawkbit/templates/ingress.yaml
> +{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
i would remove this because helm 3 likely does not work with it at the moment.
see: https://github.com/helm/helm/issues/7004

2020-11-27 15:14 UTC, monotek requested changes
The READEM.md says compatible from k8s 1.11.
Should be changed too.

2020-11-27 15:36 UTC, rpahli commented
fixed

2020-11-27 18:58 UTC, monotek approved these changes

2021-01-08 12:37 UTC, laverman commented
Thanks for your contribution. However, I'm going to close this PR in favor of #150

2021-01-08 12:37 UTC, closed without merging