Allow adding additional labels and annotations to PodSpecs
eclipse/packages pull request #389
Opened 2022-08-04 13:36 UTC by jarnfast

This PR adds the ability to add additional labels and annotations to PodSpecs on a per component basis.

Low level reasoning: I needed to inject connection secrets from HashiCorp Vault and the mutating webhook is triggered by adding the correct annotations.

I took the liberty to bump the chart version as well 😄

2022-08-05 08:01 UTC, calohmn commented
@jarnfast Thanks for the PR.
In order to contribute, you will need to agree to the Eclipse Contributor Agreement (ECA) as described on our [Contributing page](https://www.eclipse.org/packages/contribute/#the-legal-side-of-things).

2022-09-07 07:50 UTC, jarnfast commented
Sorry for the delay, I had to clear the ECA with our legal department.
ECA is now signed and I've resolved the conflict that popped up in the meantime.

2022-09-08 06:01 UTC, calohmn requested changes

2022-09-08 07:30 UTC, jarnfast commented on charts/hono/templates/_helpers.tpl
> +{{ .componentConfig.podAnnotations | toYaml }}
The `deployment.annotations` was added after I did my changes ;-)

I can probably work out something similar.

2022-09-13 11:11 UTC, jarnfast commented
@calohmn the label/annotation setup has now been reworked. Hope it's OK that I did force push of the new code 😉

2022-09-14 07:24 UTC, calohmn approved these changes
LGTM

Thanks for contributing 👍

2022-09-14 07:25 UTC, merged